### ISSUE TITLE
v1.9.6 to v1.17.3 Issues in HA 2024.11.3

### ISSUE THREAD

**Issue by amorabito** [dahlb/ha_blueair#160]
The integration does not seem to load with below error in logs

```
Logger: homeassistant.setup
Source: setup.py:334
First occurred: 9:18:32 PM (1 occurrences)
Last logged: 9:18:32 PM

Setup failed for custom integration 'ha_blueair': Unable to import component: cannot import name 'ModelEnum' from 'blueair_api' (/config/deps/lib/python3.12/site-packages/blueair_api/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1011, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1071, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/ha_blueair/__init__.py", line 19, in <module>
    from .blueair_aws_data_update_coordinator import BlueairAwsDataUpdateCoordinator
  File "/config/custom_components/ha_blueair/blueair_aws_data_update_coordinator.py", line 5, in <module>
    from blueair_api import DeviceAws as BlueAirApiDeviceAws, ModelEnum
ImportError: cannot import name 'ModelEnum' from 'blueair_api' (/config/deps/lib/python3.12/site-packages/blueair_api/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1031, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1023, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1071, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/ha_blueair/__init__.py", line 19, in <module>
    from .blueair_aws_data_update_coordinator import BlueairAwsDataUpdateCoordinator
  File "/config/custom_components/ha_blueair/blueair_aws_data_update_coordinator.py", line 5, in <module>
    from blueair_api import DeviceAws as BlueAirApiDeviceAws, ModelEnum
ImportError: cannot import name 'ModelEnum' from 'blueair_api' (/config/deps/lib/python3.12/site-packages/blueair_api/__init__.py)

**Comment by amorabito** [comment]
Solved by uninstalling blueair_api using pip like in #162
```
pip uninstall blueair_api
```
Then redownloading in HACS
