### ISSUE TITLE
Classic 480i sensors "Unavailable" after update to v1.17.6

### ISSUE THREAD

**Issue by kokoon** [dahlb/ha_blueair#169]
After a bunch of air sensors became available with recent updates, they became unavailable with one of the three 2024-12-15 releases.

**Comment by kokoon** [comment]
Not sure if this is related, but looks like it might be:
`Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:366
integration: Sensor (documentation, issues)
First occurred: 5:27:07 PM (1 occurrences)
Last logged: 5:27:07 PM

Error while setting up ha_blueair platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/ha_blueair/sensor.py", line 18, in async_setup_entry
    async_setup_entry_helper(hass, config_entry, async_add_entities,
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        entity_classes=[
        ^^^^^^^^^^^^^^^^
    ...<6 lines>...
            BlueairPM25Sensor,
            ^^^^^^^^^^^^^^^^^^
    ])
    ^^
  File "/config/custom_components/ha_blueair/entity.py", line 20, in async_setup_entry_helper
    if kls.is_implemented(coordinator):
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/config/custom_components/ha_blueair/sensor.py", line 124, in is_implemented
    return coordinator.pm1 is not NotImplemented
           ^^^^^^^^^^^^^^^
  File "/config/custom_components/ha_blueair/blueair_update_coordinator_device.py", line 60, in pm1
    return int(self.blueair_api_device.pm1)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'`

**Comment by rainwoodman** [comment]
Most likely I introduced this bug. I filed a PR that should fix this, but since I don't have a pre-AWS device I was not able to test it (which was how the regression got through).

**Comment by kokoon** [comment]
Sweet, works now. Thanks!
