### ISSUE TITLE
Error setting up entry

### ISSUE THREAD

**Issue by briansun92** [dahlb/ha_blueair#6]
I can't settting up ha_blueair with an error. And it operate in Home Assistant 2022.10.3

it's error log

Logger: homeassistant.config_entries
Source: custom_components/ha_blueair/__init__.py:56
Integration: Blueair ([documentation](https://github.com/dahlb/ha_blueair), [issues](https://github.com/dahlb/ha_blueair/issues))
First occurred: 00:40:38 (1 occurrences)
Last logged: 00:40:38

Error setting up entry briansun92@hotmail.com for ha_blueair
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/ha_blueair/__init__.py", line 56, in async_setup_entry
    _, aws_devices = await get_aws_devices(username=username, password=password, client_session=client_session)
  File "/usr/local/lib/python3.10/site-packages/blueair_api/util_bootstrap.py", line 51, in get_aws_devices
    api_devices = await api.devices()
  File "/usr/local/lib/python3.10/site-packages/blueair_api/http_aws_blueair.py", line 157, in devices
    'Authorization': f"Bearer {await self.get_access_token()}",
  File "/usr/local/lib/python3.10/site-packages/blueair_api/http_aws_blueair.py", line 151, in get_access_token
    await self.refresh_access_token()
  File "/usr/local/lib/python3.10/site-packages/blueair_api/http_aws_blueair.py", line 136, in refresh_access_token
    await self.refresh_jwt()
  File "/usr/local/lib/python3.10/site-packages/blueair_api/http_aws_blueair.py", line 120, in refresh_jwt
    await self.refresh_session()
  File "/usr/local/lib/python3.10/site-packages/blueair_api/http_aws_blueair.py", line 110, in refresh_session
    await self._post_request_with_logging_and_errors_raised(
  File "/usr/local/lib/python3.10/site-packages/blueair_api/http_aws_blueair.py", line 20, in request_with_active_session_wrapper
    raise e
  File "/usr/local/lib/python3.10/site-packages/blueair_api/http_aws_blueair.py", line 16, in request_with_active_session_wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/blueair_api/http_aws_blueair.py", line 54, in request_with_errors_wrapper
    raise AuthError(response.text())
blueair_api.errors.AuthError: <coroutine object ClientResponse.text at 0x7f669f0eb0>

**Comment by dahlb** [comment]
looks like you have used the wrong password

**Comment by briansun92** [comment]
I'm sure I'm using the correct password. And I can sign in app with the same password. But I'm in china and I'm not sure if they used different api.

**Comment by shdigitech** [comment]
Exactly the same error log in China too.

**Comment by dahlb** [comment]
I think I found the urls needed for the china region when investigating another issue.

if you can verify they work by checking out https://github.com/dahlb/blueair_api 
modify https://github.com/dahlb/blueair_api/blob/main/src/blueair_api/stub.py#L27  to 
```
        api, devices = await get_aws_devices(username=username, password=password, region="cn")
```
then run stub.py and it should login and print your device's current states

**Comment by dahlb** [comment]
v1.33.0 should allow configuration with cn region for those whose credentials work in china's region
