### ISSUE TITLE
Integration doesnt work since 2024.1.6, classic 280i

### ISSUE THREAD

**Issue by Quellweg22** [dahlb/ha_blueair#73]
Integration works well since more than 1.5 years. After update no entities, try several „new installations“.

Any experiences in the group?

THX in advance.
 
![IMG_0064](https://github.com/dahlb/ha_blueair/assets/61796565/56a065a4-7ad9-4f08-9b05-d6ebfec40460)

**Comment by fmork** [comment]
I have the exact same behavior. For me it broke at an earlier 2024.1 release (usure which one, unfortulately).

**Comment by dahlb** [comment]
are either of you able to add your logs after enabling debugging as described in the repo's readme?

**Comment by wevcore** [comment]
I have the same issue, 480i no longer working.

Here are the logs:

Logger: homeassistant.config_entries
Source: config_entries.py:406
First occurred: 3 February 2024 at 09:26:54 (5 occurrences)
Last logged: 12:57:08

Error setting up entry [my email address] for ha_blueair
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1112, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1145, in _create_connection_transport
    await waiter
  File "/usr/local/lib/python3.11/asyncio/sslproto.py", line 575, in _on_handshake_complete
    raise handshake_exc
  File "/usr/local/lib/python3.11/asyncio/sslproto.py", line 557, in _do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.11/ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ha_blueair/__init__.py", line 73, in async_setup_entry
    _, devices = await get_devices(
                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/blueair_api/util_bootstrap.py", line 27, in get_devices
    api_devices = await api.get_devices()
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/blueair_api/http_blueair.py", line 113, in get_devices
    url = f"https://{await self.get_home_host()}/v2/owner/{self.username}/device/"
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/blueair_api/http_blueair.py", line 37, in get_home_host
    self.home_host = await self._get_home_host()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/blueair_api/http_blueair.py", line 68, in _get_home_host
    await self._get_request_with_logging_and_errors_raised(
  File "/usr/local/lib/python3.11/site-packages/blueair_api/util_http.py", line 22, in request_with_logging_wrapper
    response = await func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/blueair_api/http_blueair.py", line 49, in _get_request_with_logging_and_errors_raised
    return await self.api_session.get(url=url, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 578, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1235, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1204, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 994, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host api.blueair.io:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]

**Comment by dochtie** [comment]
Same issue…

**Comment by pjtxxx** [comment]
Same issue with classic 405

Logger: aiohttp.server
Source: /usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py:421
First occurred: 19:53:07 (1 occurrences)
Last logged: 19:53:07

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1112, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1145, in _create_connection_transport
    await waiter
  File "/usr/local/lib/python3.11/asyncio/sslproto.py", line 575, in _on_handshake_complete
    raise handshake_exc
  File "/usr/local/lib/python3.11/asyncio/sslproto.py", line 557, in _do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.11/ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 233, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 320, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 416, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ha_blueair/config_flow.py", line 54, in async_step_user
    await api_cloud.get_auth_token()
  File "/usr/local/lib/python3.11/site-packages/blueair_api/http_blueair.py", line 42, in get_auth_token
    self.auth_token = await self._get_auth_token()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/blueair_api/http_blueair.py", line 83, in _get_auth_token
    url = f"https://{await self.get_home_host()}/v2/user/{self.username}/login/"
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/blueair_api/http_blueair.py", line 37, in get_home_host
    self.home_host = await self._get_home_host()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/blueair_api/http_blueair.py", line 68, in _get_home_host
    await self._get_request_with_logging_and_errors_raised(
  File "/usr/local/lib/python3.11/site-packages/blueair_api/util_http.py", line 22, in request_with_logging_wrapper
    response = await func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/blueair_api/http_blueair.py", line 49, in _get_request_with_logging_and_errors_raised
    return await self.api_session.get(url=url, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 578, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1235, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1204, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 994, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host api.blueair.io:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]

**Comment by averzicco** [comment]
The issue is caused by the incorrect configuration of the server TLS certificates. The server is returning the `*.blueair.io` certificate two times instead of returning `*.blueair.io` certificate and the intermediate CA certificate (`DigiCert Global G2 TLS RSA SHA256 2020 CA1`).

Since the `*.blueair.io` has been issued on January 29th I guess that someone updated the AWS load balancer configuration last week and uploaded the same file two times by mistake.

This is probably what happened also last year, see https://github.com/dahlb/ha_blueair/issues/12

I guess we'll have to wait until it will get fixed server side

here for reference the certificates exposed by the server:
```
openssl s_client -connect api.blueair.io:443 -showcerts
CONNECTED(00000003)
depth=0 C = SE, L = Stockholm, O = Blueair AB, CN = *.blueair.io
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 C = SE, L = Stockholm, O = Blueair AB, CN = *.blueair.io
verify error:num=21:unable to verify the first certificate
verify return:1
depth=0 C = SE, L = Stockholm, O = Blueair AB, CN = *.blueair.io
verify return:1
---
Certificate chain
 0 s:C = SE, L = Stockholm, O = Blueair AB, CN = *.blueair.io
   i:C = US, O = DigiCert Inc, CN = DigiCert Global G2 TLS RSA SHA256 2020 CA1
-----BEGIN CERTIFICATE-----
MIIGxjCCBa6gAwIBAgIQB04AXrFp3sYZybjPjTohbjANBgkqhkiG9w0BAQsFADBZ
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMTMwMQYDVQQDEypE
aWdpQ2VydCBHbG9iYWwgRzIgVExTIFJTQSBTSEEyNTYgMjAyMCBDQTEwHhcNMjQw
MTI5MDAwMDAwWhcNMjUwMjI4MjM1OTU5WjBNMQswCQYDVQQGEwJTRTESMBAGA1UE
BxMJU3RvY2tob2xtMRMwEQYDVQQKEwpCbHVlYWlyIEFCMRUwEwYDVQQDDAwqLmJs
dWVhaXIuaW8wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC9kwm7Gue6
iKuM7djk/jovQ5SHwjhUsxtr2BNcYZRNrIiZiWgu/MFQ7isC9lztpT7BN9lA+aQ2
7v1L9+QQnD0tVPxm4GUz7MDc2nzjlDStYQLFjU2kWbqlrPKST01BCAMeSJi6vkRL
A1vyxx3w85d45EHwtMUf5wwsTrEF0NV55PywTm+KHxf8SRKIJbM9xRg/darkhWA0
aA+rNRqoSi3EpvqjKKT0baAMKhbcYuyh9ZZ7Pi3zNo90+a40iPbXrAdumFcTNB6a
hZwVlGfbz33z0yKyhdcyxbSKduW6vHA+gRq6M1Jg9/jnv2aLysPlnWPnvdL0ARnC
zKw1CADPCKzLAgMBAAGjggOUMIIDkDAfBgNVHSMEGDAWgBR0hYDAZsffN97PvSk3
qgMdvu3NFzAdBgNVHQ4EFgQUrCluMLEtquNRODNyNxjegYSwm0UwIwYDVR0RBBww
GoIMKi5ibHVlYWlyLmlvggpibHVlYWlyLmlvMD4GA1UdIAQ3MDUwMwYGZ4EMAQIC
MCkwJwYIKwYBBQUHAgEWG2h0dHA6Ly93d3cuZGlnaWNlcnQuY29tL0NQUzAOBgNV
HQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMIGfBgNV
HR8EgZcwgZQwSKBGoESGQmh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2Vy
dEdsb2JhbEcyVExTUlNBU0hBMjU2MjAyMENBMS0xLmNybDBIoEagRIZCaHR0cDov
L2NybDQuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0R2xvYmFsRzJUTFNSU0FTSEEyNTYy
MDIwQ0ExLTEuY3JsMIGHBggrBgEFBQcBAQR7MHkwJAYIKwYBBQUHMAGGGGh0dHA6
Ly9vY3NwLmRpZ2ljZXJ0LmNvbTBRBggrBgEFBQcwAoZFaHR0cDovL2NhY2VydHMu
ZGlnaWNlcnQuY29tL0RpZ2lDZXJ0R2xvYmFsRzJUTFNSU0FTSEEyNTYyMDIwQ0Ex
LTEuY3J0MAwGA1UdEwEB/wQCMAAwggF+BgorBgEEAdZ5AgQCBIIBbgSCAWoBaAB2
AE51oydcmhDDOFts1N8/Uusd8OCOG41pwLH6ZLFimjnfAAABjVU6RsEAAAQDAEcw
RQIhAJplDDjZpT6Y5bID4B/vc+JMTbDUhZQBA3647VUQWDpHAiB5SwMvq0IYpp72
phADF0V/VbCJII0MkFGIXxVsB9sDqgB1AH1ZHhLheCp7HGFnfF79+NCHXBSgTpWe
uQMv2Q6MLnm4AAABjVU6RnoAAAQDAEYwRAIgXM9WjhbCFrPPL56PyeJacCIsePPg
tgQ58rcWe3yu8z8CIH70KZ821B45Mdg8aOCabuA1112ltDoUwqq30hJnnVwBAHcA
5tIxY0B3jMEQQQbXcbnOwdJA9paEhvu6hzId/R43jlAAAAGNVTpGnwAABAMASDBG
AiEAiZjs1jwYmA492C9Sd/gkK+9g48koDt/PiODaci7yX1sCIQDzeImI2RJliGlT
E7aZRxPVfep5q8x1ItUcA05X8Ied/jANBgkqhkiG9w0BAQsFAAOCAQEAbjXIueV5
lbWt5022F3H7tng6rfD8RMksfc5xhn8JMwJuO97XX5Z3lvYEl3Tkt6KIQICy7Npn
8kYMyoAXb7a4y9A/c/3xnxWiSB/tUxv98U/mGYyJThibIju1vCTCly2X8pdB88mI
mrPp+RiMOE3K9nfkA+oMKw5flPWd8DhTYl3r9UosItqOKJp4Brwh99WjC3XcETsa
IN+z8/gu5ZsK6/zUX5gglxu2UNitrWg7pTPb0YxPZeLtrA5IXacoYWO4/rOJyiAY
8a4q9eduR7utmo+3hSYkEqPqr+a6s8IY6klSoE5vsiEdeSsqdFLkVYWTn22xdlJK
9TPEPzPQ1mWEtg==
-----END CERTIFICATE-----
 1 s:C = SE, L = Stockholm, O = Blueair AB, CN = *.blueair.io
   i:C = US, O = DigiCert Inc, CN = DigiCert Global G2 TLS RSA SHA256 2020 CA1
-----BEGIN CERTIFICATE-----
MIIGxjCCBa6gAwIBAgIQB04AXrFp3sYZybjPjTohbjANBgkqhkiG9w0BAQsFADBZ
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMTMwMQYDVQQDEypE
aWdpQ2VydCBHbG9iYWwgRzIgVExTIFJTQSBTSEEyNTYgMjAyMCBDQTEwHhcNMjQw
MTI5MDAwMDAwWhcNMjUwMjI4MjM1OTU5WjBNMQswCQYDVQQGEwJTRTESMBAGA1UE
BxMJU3RvY2tob2xtMRMwEQYDVQQKEwpCbHVlYWlyIEFCMRUwEwYDVQQDDAwqLmJs
dWVhaXIuaW8wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC9kwm7Gue6
iKuM7djk/jovQ5SHwjhUsxtr2BNcYZRNrIiZiWgu/MFQ7isC9lztpT7BN9lA+aQ2
7v1L9+QQnD0tVPxm4GUz7MDc2nzjlDStYQLFjU2kWbqlrPKST01BCAMeSJi6vkRL
A1vyxx3w85d45EHwtMUf5wwsTrEF0NV55PywTm+KHxf8SRKIJbM9xRg/darkhWA0
aA+rNRqoSi3EpvqjKKT0baAMKhbcYuyh9ZZ7Pi3zNo90+a40iPbXrAdumFcTNB6a
hZwVlGfbz33z0yKyhdcyxbSKduW6vHA+gRq6M1Jg9/jnv2aLysPlnWPnvdL0ARnC
zKw1CADPCKzLAgMBAAGjggOUMIIDkDAfBgNVHSMEGDAWgBR0hYDAZsffN97PvSk3
qgMdvu3NFzAdBgNVHQ4EFgQUrCluMLEtquNRODNyNxjegYSwm0UwIwYDVR0RBBww
GoIMKi5ibHVlYWlyLmlvggpibHVlYWlyLmlvMD4GA1UdIAQ3MDUwMwYGZ4EMAQIC
MCkwJwYIKwYBBQUHAgEWG2h0dHA6Ly93d3cuZGlnaWNlcnQuY29tL0NQUzAOBgNV
HQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMIGfBgNV
HR8EgZcwgZQwSKBGoESGQmh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2Vy
dEdsb2JhbEcyVExTUlNBU0hBMjU2MjAyMENBMS0xLmNybDBIoEagRIZCaHR0cDov
L2NybDQuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0R2xvYmFsRzJUTFNSU0FTSEEyNTYy
MDIwQ0ExLTEuY3JsMIGHBggrBgEFBQcBAQR7MHkwJAYIKwYBBQUHMAGGGGh0dHA6
Ly9vY3NwLmRpZ2ljZXJ0LmNvbTBRBggrBgEFBQcwAoZFaHR0cDovL2NhY2VydHMu
ZGlnaWNlcnQuY29tL0RpZ2lDZXJ0R2xvYmFsRzJUTFNSU0FTSEEyNTYyMDIwQ0Ex
LTEuY3J0MAwGA1UdEwEB/wQCMAAwggF+BgorBgEEAdZ5AgQCBIIBbgSCAWoBaAB2
AE51oydcmhDDOFts1N8/Uusd8OCOG41pwLH6ZLFimjnfAAABjVU6RsEAAAQDAEcw
RQIhAJplDDjZpT6Y5bID4B/vc+JMTbDUhZQBA3647VUQWDpHAiB5SwMvq0IYpp72
phADF0V/VbCJII0MkFGIXxVsB9sDqgB1AH1ZHhLheCp7HGFnfF79+NCHXBSgTpWe
uQMv2Q6MLnm4AAABjVU6RnoAAAQDAEYwRAIgXM9WjhbCFrPPL56PyeJacCIsePPg
tgQ58rcWe3yu8z8CIH70KZ821B45Mdg8aOCabuA1112ltDoUwqq30hJnnVwBAHcA
5tIxY0B3jMEQQQbXcbnOwdJA9paEhvu6hzId/R43jlAAAAGNVTpGnwAABAMASDBG
AiEAiZjs1jwYmA492C9Sd/gkK+9g48koDt/PiODaci7yX1sCIQDzeImI2RJliGlT
E7aZRxPVfep5q8x1ItUcA05X8Ied/jANBgkqhkiG9w0BAQsFAAOCAQEAbjXIueV5
lbWt5022F3H7tng6rfD8RMksfc5xhn8JMwJuO97XX5Z3lvYEl3Tkt6KIQICy7Npn
8kYMyoAXb7a4y9A/c/3xnxWiSB/tUxv98U/mGYyJThibIju1vCTCly2X8pdB88mI
mrPp+RiMOE3K9nfkA+oMKw5flPWd8DhTYl3r9UosItqOKJp4Brwh99WjC3XcETsa
IN+z8/gu5ZsK6/zUX5gglxu2UNitrWg7pTPb0YxPZeLtrA5IXacoYWO4/rOJyiAY
8a4q9eduR7utmo+3hSYkEqPqr+a6s8IY6klSoE5vsiEdeSsqdFLkVYWTn22xdlJK
9TPEPzPQ1mWEtg==
-----END CERTIFICATE-----
---
Server certificate
subject=C = SE, L = Stockholm, O = Blueair AB, CN = *.blueair.io

issuer=C = US, O = DigiCert Inc, CN = DigiCert Global G2 TLS RSA SHA256 2020 CA1

---
No client certificate CA names sent
Peer signing digest: SHA512
Peer signature type: RSA
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 3986 bytes and written 438 bytes
Verification error: unable to verify the first certificate
```

**Comment by dahlb** [comment]
Thanks for the clear insight into this issue @averzicco

**Comment by ArthurianX** [comment]
So we just wait, thanks!

**Comment by you96** [comment]
Does it work now?

**Comment by wevcore** [comment]
Yes, mine does :)
