### ISSUE TITLE
Add support for aws region used in europe

### ISSUE THREAD

**Issue by oestreicher42** [dahlb/ha_blueair#8]
Hi,
I try to connect to my blueair account using version 1.6.2 of ha_blueair on home assistant core 2023.1.1.
Unfortunately I get authentication failures after trying to set up the connection. username/password do work, so the issue seems to be somewhere else.
Here ist the debug log:
Logger: homeassistant.config_entries
Source: custom_components/ha_blueair/__init__.py:58
Integration: Blueair ([documentation](https://github.com/dahlb/ha_blueair), [issues](https://github.com/dahlb/ha_blueair/issues))
First occurred: 6 January 2023 at 19:07:12 (5 occurrences)
Last logged: 21:18:26

Error setting up entry [my_email_address] for ha_blueair
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/ha_blueair/__init__.py", line 58, in async_setup_entry
    _, aws_devices = await get_aws_devices(
  File "/usr/local/lib/python3.10/site-packages/blueair_api/util_bootstrap.py", line 51, in get_aws_devices
    api_devices = await api.devices()
  File "/usr/local/lib/python3.10/site-packages/blueair_api/http_aws_blueair.py", line 157, in devices
    'Authorization': f"Bearer {await self.get_access_token()}",
  File "/usr/local/lib/python3.10/site-packages/blueair_api/http_aws_blueair.py", line 151, in get_access_token
    await self.refresh_access_token()
  File "/usr/local/lib/python3.10/site-packages/blueair_api/http_aws_blueair.py", line 136, in refresh_access_token
    await self.refresh_jwt()
  File "/usr/local/lib/python3.10/site-packages/blueair_api/http_aws_blueair.py", line 120, in refresh_jwt
    await self.refresh_session()
  File "/usr/local/lib/python3.10/site-packages/blueair_api/http_aws_blueair.py", line 110, in refresh_session
    await self._post_request_with_logging_and_errors_raised(
  File "/usr/local/lib/python3.10/site-packages/blueair_api/http_aws_blueair.py", line 20, in request_with_active_session_wrapper
    raise e
  File "/usr/local/lib/python3.10/site-packages/blueair_api/http_aws_blueair.py", line 16, in request_with_active_session_wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/blueair_api/http_aws_blueair.py", line 54, in request_with_errors_wrapper
    raise AuthError(await response.text())
blueair_api.errors.AuthError: {
  "callId": "a4c25467229f4e69bd66d4454c236cbd",
  "errorCode": 403042,
  "errorDetails": "invalid loginID or password",
  "errorMessage": "Invalid LoginID",
  "apiVersion": 2,
  "statusCode": 403,
  "statusReason": "Forbidden",
  "time": "2023-01-06T18:07:12.475Z"
}

Do I miss a step?
Dominik

**Comment by dahlb** [comment]
guessing this is a regionality issue, where abouts are you located?

**Comment by oestreicher42** [comment]
Germany

**Comment by oestreicher42** [comment]
If it helps. My mobile seems to contact the following domains when using the android app:
on port 443:
api.blueair.io
api-eu-west-1.blueair.io
a3tpdpjvxk6yog-ats.iot.eu-west-1.amazonaws.com
hkgmr8v960.execute-api.eu-west-1.amazonaws.com

on port 61614:
*.blueair.io
34.243.128.96

**Comment by dsv591** [comment]
Same issue here. I'm located in Costa Rica, but my account is created in EU.

I can confirm this because the US website does not recognize my credentials but France website does.

**Comment by dsv591** [comment]
@dahlb, I see your `const.py` file in the blueair_api project already has the keys for eu.

Is it only the parameter in setup that is missing? seems like API classes can already take a region parameter (it has `us` as the default value right now)

**Comment by dahlb** [comment]
@dsv591 that is a good point, I made up https://github.com/dahlb/ha_blueair/tree/eu_support if you can test it out, I verified it still worked in us

**Comment by dsv591** [comment]
@dahlb no luck, I still get the same invalid login error message.

is there a way I can check the call is going to the right endpoint?

**Comment by dahlb** [comment]
blueair_api from the steps below should show you the end point you are hitting

You can enable logging for this integration specifically and share your logs, so I can have a deep dive investigation. To enable logging, update your configuration.yaml like this, we can get more information in Configuration -> Logs page
```
logger:
  default: warning
  logs:
    custom_components.ha_blueair: debug
    blueair_api: debug
```

**Comment by dsv591** [comment]
I added the logger configuration but I don't think I'm getting anything extra

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/ha_blueair/__init__.py", line 62, in async_setup_entry
    aws_api, aws_devices = await get_aws_devices(
  File "/usr/local/lib/python3.10/site-packages/blueair_api/util_bootstrap.py", line 51, in get_aws_devices
    api_devices = await api.devices()
  File "/usr/local/lib/python3.10/site-packages/blueair_api/http_aws_blueair.py", line 157, in devices
    'Authorization': f"Bearer {await self.get_access_token()}",
  File "/usr/local/lib/python3.10/site-packages/blueair_api/http_aws_blueair.py", line 151, in get_access_token
    await self.refresh_access_token()
  File "/usr/local/lib/python3.10/site-packages/blueair_api/http_aws_blueair.py", line 136, in refresh_access_token
    await self.refresh_jwt()
  File "/usr/local/lib/python3.10/site-packages/blueair_api/http_aws_blueair.py", line 120, in refresh_jwt
    await self.refresh_session()
  File "/usr/local/lib/python3.10/site-packages/blueair_api/http_aws_blueair.py", line 110, in refresh_session
    await self._post_request_with_logging_and_errors_raised(
  File "/usr/local/lib/python3.10/site-packages/blueair_api/http_aws_blueair.py", line 20, in request_with_active_session_wrapper
    raise e
  File "/usr/local/lib/python3.10/site-packages/blueair_api/http_aws_blueair.py", line 16, in request_with_active_session_wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/blueair_api/http_aws_blueair.py", line 54, in request_with_errors_wrapper
    raise AuthError(await response.text())
blueair_api.errors.AuthError: {

  "callId": "4f79ccca3259412d8b93058d78127522",

  "errorCode": 403042,

  "errorDetails": "invalid loginID or password",

  "errorMessage": "Invalid LoginID",

  "apiVersion": 2,

  "statusCode": 403,

  "statusReason": "Forbidden",

  "time": "2023-01-28T17:22:04.846Z"

}

**Comment by dsv591** [comment]
Looking at the network trace from the website login, looks like the call should be going to https://accounts.eu1.gigya.com/

**Comment by dsv591** [comment]
It's interesting because although my homehost is still US, my account host should be EU

**Comment by dsv591** [comment]
Btw I was able to make the custom component work forcing the region value to 'eu' in init.py

Here are the logs in case they help (access tokens and emails removed)

2023-01-28 11:58:42.763 DEBUG (MainThread) [blueair_api.util_http] response headers:<CIMultiDict('Content-Encoding': 'gzip', 'Content-Type': 'application/json;charset=UTF-8', 'Date': 'Sat, 28 Jan 2023 17:58:42 GMT', 'Server': 'nginx/1.12.1', 'Vary': 'Accept-Encoding,Accept-Encoding', 'X-AUTH-TOKEN': 'REMOVED', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive')>
2023-01-28 11:58:42.764 DEBUG (MainThread) [blueair_api.util_http] response status: 200
2023-01-28 11:58:42.764 DEBUG (MainThread) [blueair_api.util_http] response raw: true
2023-01-28 11:58:42.764 DEBUG (MainThread) [blueair_api.util_http] sending https://api-us-east-1.blueair.io/v2/owner/xxxxxx@gmail.com/device/ requestheaders: {'X-API-KEY-TOKEN': 'eyJhbGciOiJIUzI1NiJ9.eyJncmFudGVlIjoiYmx1ZWFpciIsImlhdCI6MTQ1MzEyNTYzMiwidmFsaWRpdHkiOi0xLCJqdGkiOiJkNmY3OGE0Yi1iMWNkLTRkZDgtOTA2Yi1kN2JkNzM0MTQ2NzQiLCJwZXJtaXNzaW9ucyI6WyJhbGwiXSwicXVvdGEiOi0xLCJyYXRlTGltaXQiOi0xfQ.CJsfWVzFKKDDA6rWdh-hjVVVE9S3d6Hu9BzXG9htWFw', 'X-AUTH-TOKEN': 'REMOVED'}
2023-01-28 11:58:42.909 DEBUG (MainThread) [blueair_api.util_http] response headers:<CIMultiDict('Content-Encoding': 'gzip', 'Content-Type': 'application/json;charset=UTF-8', 'Date': 'Sat, 28 Jan 2023 17:58:42 GMT', 'Server': 'nginx/1.12.1', 'Vary': 'Accept-Encoding,Accept-Encoding', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive')>
2023-01-28 11:58:42.909 DEBUG (MainThread) [blueair_api.util_http] response status: 200
2023-01-28 11:58:42.909 DEBUG (MainThread) [blueair_api.util_http] response raw: []
2023-01-28 11:58:42.911 DEBUG (MainThread) [blueair_api.http_aws_blueair] session
2023-01-28 11:58:42.912 DEBUG (MainThread) [blueair_api.http_aws_blueair] checking for errors
2023-01-28 11:58:42.912 DEBUG (MainThread) [blueair_api.util_http] sending https://accounts.eu1.gigya.com/accounts.login request
2023-01-28 11:58:43.825 DEBUG (MainThread) [blueair_api.util_http] response headers:<CIMultiDict('Content-Length': '750', 'Content-Type': 'text/javascript; charset=utf-8', 'Date': 'Sat, 28 Jan 2023 17:58:43 GMT', 'Cache-Control': 'private', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'p3p': 'CP="IDC COR PSA DEV ADM OUR IND ONL"', 'x-error-code': '0', 'x-soa': 'true, Gator', 'x-server': 'eu1a-nomad-g14', 'x-callid': 'd92e6e5e730b4246a13473a631c352d9', 'x-robots-tag': 'none')>
2023-01-28 11:58:43.825 DEBUG (MainThread) [blueair_api.util_http] response status: 200
2023-01-28 11:58:43.827 DEBUG (MainThread) [blueair_api.util_http] response json: {'callId': 'd92e6e5e730b4246a13473a631c352d9', 'errorCode': 0, 'apiVersion': 2, 'statusCode': 200, 'statusReason': 'OK', 'time': '2023-01-28T17:58:43.740Z', 'registeredTimestamp': 1674357980, 'UID': 'a9ded29452ce42efa20a7b3433604033', 'UIDSignature': 'WyG+esOD4kYpNe48hJer5Ru+8Ys=', 'signatureTimestamp': '1674928723', 'created': '2023-01-22T03:26:20.588Z', 'createdTimestamp': 1674357980, 'isActive': True, 'isRegistered': True, 'isVerified': False, 'lastLogin': '2023-01-28T17:58:43.711Z', 'lastLoginTimestamp': 1674928723, 'lastUpdated': '2023-01-28T17:32:02.298Z', 'lastUpdatedTimestamp': 1674927122298, 'loginProvider': 'site', 'oldestDataUpdated': '2023-01-22T03:26:20.588Z', 'oldestDataUpdatedTimestamp': 1674357980588, 'profile': {'firstName': 'Daniel', 'lastName': 'Salazar', 'email': 'xxxxxx@gmail.com'}, 'registered': '2023-01-22T03:26:20.815Z', 'socialProviders': 'site', 'newUser': False, 'sessionInfo': {'sessionToken': 'REMOVED', 'sessionSecret': 'REMOVED', 'expires_in': '0'}}
2023-01-28 11:58:43.828 DEBUG (MainThread) [blueair_api.http_aws_blueair] response json found, checking status code from response
2023-01-28 11:58:43.828 DEBUG (MainThread) [blueair_api.http_aws_blueair] response 200
2023-01-28 11:58:43.845 DEBUG (MainThread) [blueair_api.http_aws_blueair] session
2023-01-28 11:58:43.846 DEBUG (MainThread) [blueair_api.http_aws_blueair] checking for errors
2023-01-28 11:58:43.846 DEBUG (MainThread) [blueair_api.util_http] sending https://accounts.eu1.gigya.com/accounts.getJWT request
2023-01-28 11:58:44.071 DEBUG (MainThread) [blueair_api.util_http] response headers:<CIMultiDict('Content-Length': '814', 'Content-Type': 'text/javascript; charset=utf-8', 'Date': 'Sat, 28 Jan 2023 17:58:43 GMT', 'Cache-Control': 'private', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'p3p': 'CP="IDC COR PSA DEV ADM OUR IND ONL"', 'x-error-code': '0', 'x-soa': 'true, Gator', 'x-server': 'eu1a-nomad-g10', 'x-callid': '945bf7cd8698471aad652ac9ac792b28', 'x-robots-tag': 'none')>
2023-01-28 11:58:44.071 DEBUG (MainThread) [blueair_api.util_http] response status: 200
2023-01-28 11:58:44.134 DEBUG (MainThread) [blueair_api.util_http] response json: {'callId': '945bf7cd8698471aad652ac9ac792b28', 'errorCode': 0, 'apiVersion': 2, 'statusCode': 200, 'statusReason': 'OK', 'time': '2023-01-28T17:58:43.965Z', 'id_token': 'REMOVED'}
2023-01-28 11:58:44.134 DEBUG (MainThread) [blueair_api.http_aws_blueair] response json found, checking status code from response
2023-01-28 11:58:44.178 DEBUG (MainThread) [blueair_api.http_aws_blueair] response 200
2023-01-28 11:58:44.179 DEBUG (MainThread) [blueair_api.http_aws_blueair] session
2023-01-28 11:58:44.180 DEBUG (MainThread) [blueair_api.http_aws_blueair] checking for errors
2023-01-28 11:58:44.180 DEBUG (MainThread) [blueair_api.util_http] sending https://hkgmr8v960.execute-api.eu-west-1.amazonaws.com/prod/c/login requestheaders: {'idtoken': 'REMOVED'}
2023-01-28 11:58:46.463 DEBUG (MainThread) [blueair_api.util_http] response headers:<CIMultiDict('Date': 'Sat, 28 Jan 2023 17:58:46 GMT', 'Content-Type': 'application/json', 'Content-Length': '3011', 'Connection': 'keep-alive', 'x-amzn-RequestId': '019ec47b-0d0a-4350-857f-d36b9a94f5ef', 'Content-Encoding': 'gzip', 'Strict-Transport-Security': '3000', 'Content-Security-Policy': "default-src 'none'", 'x-amz-apigw-id': 'fdxNVE9mDoEFykg=', 'x-amzn-Remapped-Server': '', 'X-Content-Type-Options': 'nosniff', 'X-Custom-Header': 'application/json', 'X-Amzn-Trace-Id': 'Root=1-63d56255-2f5075ab2497553b62aeb1b8')>
2023-01-28 11:58:46.463 DEBUG (MainThread) [blueair_api.util_http] response status: 200
2023-01-28 11:58:46.464 DEBUG (MainThread) [blueair_api.util_http] response json: {'access_token': 'REMOVED', 'ba_X-Amz-CustomAuthorizer-Signature': 'REMOVED', 'id_token': 'REMOVED', 'ba_X-Amz-CustomAuthorizer-Name': 'custom-authorizer', 'ba_X-Amz-CustomAuthorizer-Token': 'REMOVED', 'token_type': 'Bearer', 'expires_in': '86400'}
2023-01-28 11:58:46.465 DEBUG (MainThread) [blueair_api.http_aws_blueair] response 200
2023-01-28 11:58:46.465 DEBUG (MainThread) [blueair_api.http_aws_blueair] session
2023-01-28 11:58:46.465 DEBUG (MainThread) [blueair_api.http_aws_blueair] checking for errors
2023-01-28 11:58:46.465 DEBUG (MainThread) [blueair_api.util_http] sending https://hkgmr8v960.execute-api.eu-west-1.amazonaws.com/prod/c/registered-devices requestheaders: {'Authorization': 'REMOVED'}
2023-01-28 11:58:47.260 DEBUG (MainThread) [blueair_api.util_http] response headers:<CIMultiDict('Date': 'Sat, 28 Jan 2023 17:58:47 GMT', 'Content-Type': 'application/json', 'Content-Length': '176', 'Connection': 'keep-alive', 'x-amzn-RequestId': '101fdc3c-a990-4d27-8cee-8cb3ef4b277f', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Strict-Transport-Security': '3000', 'Content-Security-Policy': "default-src 'none'", 'x-amz-apigw-id': 'fdxNjEj5joEF1UA=', 'X-Content-Type-Options': 'nosniff', 'X-Custom-Header': 'application/json', 'X-Amzn-Trace-Id': 'Root=1-63d56256-432239070d9f0a0616e97acf')>
2023-01-28 11:58:47.260 DEBUG (MainThread) [blueair_api.util_http] response status: 200
2023-01-28 11:58:47.260 DEBUG (MainThread) [blueair_api.util_http] response json: {'devices': [{'name': '516fdde6-92e1-4e39-83d6-ae5ceaa09714', 'wifi-firmware': '2.1.1', 'mcu-firmware': '1.0.12', 'type': 'G4', 'uuid': '1e035f33-592d-4787-bd93-440491cbdf5d', 'mac': '40:f5:20:55:a2:c8', 'user-type': 'Root'}]}
2023-01-28 11:58:47.260 DEBUG (MainThread) [blueair_api.http_aws_blueair] response 200
2023-01-28 11:58:47.260 DEBUG (MainThread) [blueair_api.device_aws] creating blueair device: 1e035f33-592d-4787-bd93-440491cbdf5d
2023-01-28 11:58:47.261 DEBUG (MainThread) [blueair_api.http_aws_blueair] session
2023-01-28 11:58:47.261 DEBUG (MainThread) [blueair_api.http_aws_blueair] checking for errors
2023-01-28 11:58:47.261 DEBUG (MainThread) [blueair_api.util_http] sending https://hkgmr8v960.execute-api.eu-west-1.amazonaws.com/prod/c/516fdde6-92e1-4e39-83d6-ae5ceaa09714/r/initial requestheaders: {'Authorization': 'REMOVED'}sending https://hkgmr8v960.execute-api.eu-west-1.amazonaws.com/prod/c/516fdde6-92e1-4e39-83d6-ae5ceaa09714/r/initial request with {'deviceconfigquery': [{'id': '1e035f33-592d-4787-bd93-440491cbdf5d', 'r': {'r': ['sensors']}}], 'includestates': True, 'eventsubscription': {'include': [{'filter': {'o': '= 1e035f33-592d-4787-bd93-440491cbdf5d'}}]}}
2023-01-28 11:58:48.446 DEBUG (MainThread) [blueair_api.util_http] response headers:<CIMultiDict('Date': 'Sat, 28 Jan 2023 17:58:48 GMT', 'Content-Type': 'application/json', 'Content-Length': '1938', 'Connection': 'keep-alive', 'x-amzn-RequestId': 'd43dac70-088d-48cd-b57d-d68645cd7031', 'Content-Encoding': 'gzip', 'x-amz-apigw-id': 'fdxNsHuxDoEFvIw=', 'X-Amzn-Trace-Id': 'Root=1-63d56257-6b0b8859704d0a6d2ee56c2b')>
2023-01-28 11:58:48.447 DEBUG (MainThread) [blueair_api.util_http] response status: 200
2023-01-28 11:58:48.448 DEBUG (MainThread) [blueair_api.util_http] response json: {REMOVED}
2023-01-28 11:58:48.449 DEBUG (MainThread) [blueair_api.http_aws_blueair] response 200
2023-01-28 11:58:48.450 DEBUG (MainThread) [blueair_api.callbacks] Purificador de la sala publishing updates
2023-01-28 11:58:48.450 DEBUG (MainThread) [custom_components.ha_blueair.blueair_aws_data_update_coordinator] Finished fetching ha_blueair-Purificador de la sala data in 1.189 seconds (success: True)


Hope this helps, this at least shows that the code that works in US works in EU as well.

**Comment by dahlb** [comment]
@dsv591 thanks for all those logs, please pull the updates for eu_support branch and let me know if it works for you now. you will have to delete and re-add the integration, but now there is just an option in the config flow that lets you pick your region to us.  I had tried to pick based on the blue air region used in the classic api, but it appear to just always use us even for you whose protect api needs eu so the user will have to pick.

**Comment by dsv591** [comment]
As expected, the initial configuration still works! yay!

However, I'm noticing something I noticed today, which is that there is no auto update of the sensors.

I believe these lines are the culprit as you can see the 2nd API is going to US (because the homehost API still returns US for some reason)

2023-01-29 08:30:22.100 DEBUG (MainThread) [blueair_api.util_http] sending https://api.blueair.io/v2/user/xxxxxx@gmail.com/homehost/ requestheaders: {'X-API-KEY-TOKEN': 'REMOVED}
2023-01-29 08:30:23.911 DEBUG (MainThread) [blueair_api.util_http] response headers:<CIMultiDict('Content-Encoding': 'gzip', 'Content-Type': 'application/json;charset=UTF-8', 'Date': 'Sun, 29 Jan 2023 14:30:23 GMT', 'Server': 'nginx/1.12.1', 'Vary': 'Accept-Encoding,Accept-Encoding', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive')>
2023-01-29 08:30:23.912 DEBUG (MainThread) [blueair_api.util_http] response status: 200
2023-01-29 08:30:23.914 DEBUG (MainThread) [blueair_api.util_http] response raw: "api-us-east-1.blueair.io"
2023-01-29 08:30:23.914 DEBUG (MainThread) [blueair_api.util_http] sending https://api-us-east-1.blueair.io/v2/user/xxxxxx@gmail.com/login/ requestheaders: {'X-API-KEY-TOKEN': 'REMOVED', 'Authorization': 'REMOVED'}
2023-01-29 08:30:25.466 DEBUG (MainThread) [blueair_api.util_http] response headers:<CIMultiDict('Content-Encoding': 'gzip', 'Content-Type': 'application/json;charset=UTF-8', 'Date': 'Sun, 29 Jan 2023 14:30:25 GMT', 'Server': 'nginx/1.12.1', 'Vary': 'Accept-Encoding,Accept-Encoding', 'X-AUTH-TOKEN': 'REMOVED', 'Content-Length': '30', 'Connection': 'keep-alive')>
2023-01-29 08:30:25.466 DEBUG (MainThread) [blueair_api.util_http] response status: 200
2023-01-29 08:30:25.467 DEBUG (MainThread) [blueair_api.util_http] response raw: true
2023-01-29 08:30:25.467 DEBUG (MainThread) [blueair_api.util_http] sending https://api-us-east-1.blueair.io/v2/owner/xxxxxx@gmail.com/device/ requestheaders: {'X-API-KEY-TOKEN': 'REMOVED', 'X-AUTH-TOKEN': 'REMOVED'}
2023-01-29 08:30:25.620 DEBUG (MainThread) [blueair_api.util_http] response headers:<CIMultiDict('Content-Encoding': 'gzip', 'Content-Type': 'application/json;charset=UTF-8', 'Date': 'Sun, 29 Jan 2023 14:30:25 GMT', 'Server': 'nginx/1.12.1', 'Vary': 'Accept-Encoding,Accept-Encoding', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive')>
2023-01-29 08:30:25.620 DEBUG (MainThread) [blueair_api.util_http] response status: 200
2023-01-29 08:30:25.620 DEBUG (MainThread) [blueair_api.util_http] response raw: []
2023-01-29 08:30:25.627 DEBUG (MainThread) [blueair_api.http_aws_blueair] session

Since no devices are returned, I think the blueair_data_update_coordinator is not being setup correctly, but can't tell for sure if this is the devices data used to set it up.

The interesting thing is that every 3 hours data does seem to refresh, (I can see this from the logs from last night), although according to the code it should be every 10 minutes)

**Comment by dsv591** [comment]
How often should I expect sensors to update?

As per the code I think it should be every 10 minutes, but I'm not seeing consistent results.

Not sure if it has anything to do with this call still going to us due to the homehost API

2023-01-29 08:30:22.100 DEBUG (MainThread) [blueair_api.util_http] sending https://api.blueair.io/v2/user/xxxxxx@gmail.com/homehost/ requestheaders: {'X-API-KEY-TOKEN': 'REMOVED}
2023-01-29 08:30:23.911 DEBUG (MainThread) [blueair_api.util_http] response headers:<CIMultiDict('Content-Encoding': 'gzip', 'Content-Type': 'application/json;charset=UTF-8', 'Date': 'Sun, 29 Jan 2023 14:30:23 GMT', 'Server': 'nginx/1.12.1', 'Vary': 'Accept-Encoding,Accept-Encoding', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive')>
2023-01-29 08:30:23.912 DEBUG (MainThread) [blueair_api.util_http] response status: 200
2023-01-29 08:30:23.914 DEBUG (MainThread) [blueair_api.util_http] response raw: "api-us-east-1.blueair.io"
2023-01-29 08:30:23.914 DEBUG (MainThread) [blueair_api.util_http] sending https://api-us-east-1.blueair.io/v2/user/xxxxxx@gmail.com/login/ requestheaders: {'X-API-KEY-TOKEN': 'REMOVED', 'Authorization': 'REMOVED'}
2023-01-29 08:30:25.466 DEBUG (MainThread) [blueair_api.util_http] response headers:<CIMultiDict('Content-Encoding': 'gzip', 'Content-Type': 'application/json;charset=UTF-8', 'Date': 'Sun, 29 Jan 2023 14:30:25 GMT', 'Server': 'nginx/1.12.1', 'Vary': 'Accept-Encoding,Accept-Encoding', 'X-AUTH-TOKEN': 'REMOVED', 'Content-Length': '30', 'Connection': 'keep-alive')>
2023-01-29 08:30:25.466 DEBUG (MainThread) [blueair_api.util_http] response status: 200
2023-01-29 08:30:25.467 DEBUG (MainThread) [blueair_api.util_http] response raw: true
2023-01-29 08:30:25.467 DEBUG (MainThread) [blueair_api.util_http] sending https://api-us-east-1.blueair.io/v2/owner/xxxxxx@gmail.com/device/ requestheaders: {'X-API-KEY-TOKEN': 'REMOVED', 'X-AUTH-TOKEN': 'REMOVED'}
2023-01-29 08:30:25.620 DEBUG (MainThread) [blueair_api.util_http] response headers:<CIMultiDict('Content-Encoding': 'gzip', 'Content-Type': 'application/json;charset=UTF-8', 'Date': 'Sun, 29 Jan 2023 14:30:25 GMT', 'Server': 'nginx/1.12.1', 'Vary': 'Accept-Encoding,Accept-Encoding', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive')>
2023-01-29 08:30:25.620 DEBUG (MainThread) [blueair_api.util_http] response status: 200
2023-01-29 08:30:25.620 DEBUG (MainThread) [blueair_api.util_http] response raw: []
2023-01-29 08:30:25.627 DEBUG (MainThread) [blueair_api.http_aws_blueair] session

(device list returns empty array)

**Comment by dahlb** [comment]
eu support should be added in v1.7.0

we can look into the update interval in another ticket, it should be every 10 minutes but I normally do all changes from ha so i might not have noticed if it isn't

as for the homehost thing, that is because blueair has at least two completely separate api, the homehost thing is where the classic series filters are and the us/eu one is where protect filters are (might be more series on each but those are the two series I use)
